version: '3.1'
volumes:
  PhoneBookDb:
services:
  database:
    image: "postgres:13.3-alpine3.14"
    ports:
    - 5425:5432
    environment:
      POSTGRES_USER: book_usr
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: phonebook_db
      PGDATA: /data
    volumes:
    - PhoneBookDb:/data