# Generated by Django 3.2.5 on 2021-07-14 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='first name')),
                ('last', models.CharField(max_length=60, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 11 digits allowed.", regex='/^09[0-9]{9}$/gm')], verbose_name='phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phonebook',
            constraint=models.UniqueConstraint(fields=('user', 'phone_number'), name='user_num'),
        ),
    ]
