# Generated by Django 3.2.5 on 2021-07-19 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 11 digits allowed.", regex='^09[0-9]{9}$')], verbose_name='phone number'),
        ),
    ]
